## 1. Creation of Numpy arrays:

In [1]:
import numpy as np
#Numpy is not included in python as it's an external library. Here it's imported as 'np'.

### (a) Using np.array() / 1-D and 2-D:

In [8]:
arr1=np.array([2,3,6,7])
#np.array(list_of_numbers) returns an array with that list
arr1

array([2, 3, 6, 7])

In [9]:
type(arr1)
#Output means arr1 is one n-d type array under numpy library

numpy.ndarray

In [11]:
arr2=np.array([[1,2,3],[4,5,6]])
#2-d array
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### (b) Use of np.zeros / ones / empty / random():

In [13]:
arr3=np.zeros([2,3])
#Creates a n-d array of given shape, all the elements of which are zero
arr3
#Used for initialisation of an array in hurry

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr4=np.ones([3,3])
#Same function as zeros, all the elements will be one this time
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### (c) Use of np.arange:

In [17]:
arr6=np.arange(10)
#Same cocept of 'for i in range (initial value, ending value+1, gap between each numbers)'
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr7=np.arange(5,16,2)
arr7

array([ 5,  7,  9, 11, 13, 15])

### (d) Use of np.linspace():

In [19]:
arr8=np.linspace(10,20,5)
#np.linspace(starting_value, ending_value, no._of_numbers)
arr8
#Array of linearly spaced consecutive values in given range **In which starting_value and ending_value will always bbe included
#Difference between each consecutive elements will be always same
#Difference between cosecutive numbers= (ending_value - starting_value)/(no._of_numbers-1)

array([10. , 12.5, 15. , 17.5, 20. ])

### (e) Use of copy():

In [20]:
arr9=arr8.copy()
#Copy one array's elements in another array variable
arr9

array([10. , 12.5, 15. , 17.5, 20. ])

### (f) Use of identity():

In [16]:
arr5=np.identity(5)
#Concept of Identity matrix, used for initialisation
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2. Numpy Array Vs Python Lists:

### (a) Less memory proof:

In [4]:
import sys

In [3]:
lista=range(100)
arr11=np.arange(100)

In [6]:
print(sys.getsizeof(87)*len(lista))
#Memory occupied by list in bytes

2800


In [7]:
print(arr11.itemsize*arr11.size)
#Memory occupied by array in bytes

400


In [8]:
#Numpy array occupies less amount of memory which is suitable for ML

### (b) Faster execution & Convenient proof:

In [11]:
import time
#For speed measure

In [14]:
x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()
c=[x+y for x,y in zip (x,y)]
print(time.time()-start_time)

1.1488103866577148


In [15]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start_time=time.time()
c=a+b #This syntax is very easy compared to list syntax in previous cell, Hence more convenient
print(time.time()-start_time)

0.23667669296264648


In [16]:
#Numpy array is more faster than python & more convenient also.

## 3. Indexing, Slicing and Iteration: